sudo: required
services: 
  - docker

before_install:
  - docker build -t sharmad6/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  sharmad6/react-test npm test -- --coverage

after_success:
  - docker build -t sharmad6/multi-client ./client
  - docker build -t sharmad6/multi-nginx ./nginx
  - docker build -t sharmad6/multi-server ./server
  - docker build -t sharmad6/multi-worker ./worker

  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sharmad6/multi-client
  - docker push sharmad6/multi-nginx
  - docker push sharmad6/multi-server
  - docker push sharmad6/multi-server
